@startuml
top to bottom direction

skinparam classStyle rectangle
skinparam packageStyle rectilinear
skinparam classIconSize 0
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide circle

class "main.cpp" as Main <<module>> {
  +pwm: Adafruit_PWMServoDriver
  +tsl: Adafruit_TSL2591
  +setup()
  +loop()
}

class "pwm_control.cpp" as PWMControl <<module>> {
  +extern pwm: Adafruit_PWMServoDriver
  +fade_state : FadeState
  +setup_pwm() : void
  +get_pwm(int channel) : int
  +fade_led(int channel, int start_value, int end_value, int delay_ms) : void
  +fade_led_async(int channel, int start_value, int end_value, int duration_ms, int step_size = 1) : void
  +update_pwm_fade() : void
  +is_fade_active() : bool
  +stop_fade() : void


}

class "sensor_control.cpp" as SensorControl <<module>> {
  +extern tsl: Adafruit_TSL2591
  +extern pwm: Adafruit_PWMServoDriver
  +lux_state: LuxSampleState
  +ambient_offset : float
  +ambient_calibrated : bool
  +last_sample_time: unsigned long
  +integration_time_ms: uint16_t
  +SAMPLE_INTERVAL_MS: const unsigned long
  +calibrate_ambient() : void
  +init_light_sensor() : void
  +read_lux_value() : float
  +calculate_pwm_duty_cycle(float lux) : int
  +integration_time_to_ms(tsl2591IntegrationTime_t integration_time) : uint16_t
  +sensor_control_update() : void
}




class "Adafruit_PWMServoDriver" as PWMDriver <<external>>
class "Adafruit_TSL2591" as TSL2591 <<external>>
class "Wire / I2C" as I2C <<external>>
class "Arduino Core" as ArduinoCore <<external>>



Main "1"..> "1" PWMControl : setup_pwm()\nupdate()
Main "1"..> "1" SensorControl : init + update

SensorControl "1" --> "1" TSL2591 : \n\n \nreads lux
SensorControl "1"..> "1" PWMControl : set/update PWM
PWMControl "1" --> "1" PWMDriver : controls PWM
SensorControl "1"..> "1" I2C : sensor comm

Main "1"..> "1" ArduinoCore : \n\n\n\n\n\n\n\n\n\n\n\nSerial, Wire, timing \n

Main -[hidden]-> PWMControl
PWMControl -[hidden]-> SensorControl


PWMDriver -[hidden]-> TSL2591
TSL2591 -[hidden]-> I2C
I2C -[hidden]-> ArduinoCore


@enduml